name: Publish Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: autobuild-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare version
        run: |
          apt update && apt install -y --no-install-recommands make
          echo "OPEN_SNELL_VERSION=$(make version)" >> "${GITHUB_ENV}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: icpz
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build server and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            target=server
            version=${{ env.OPEN_SNELL_VERSION }}
          tags: 'icpz/snell-server:latest,ghcr.io/icpz/snell-server:latest'

      - name: Build client and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            target=client
            version=${{ env.OPEN_SNELL_VERSION }}
          tags: 'icpz/snell-client:latest,ghcr.io/icpz/snell-client:latest'

